const ADD_TASK = "ADD_TASK";
const REMOVE_TASK = "REMOVE_TASK";
const DONE_TASK = "DONE_TASK";
const CHANGE_FILTER = "CHANGE_FILTER";
const SHOW_ALL = "SHOW_ALL";
const SHOW_ACTIVE = "SHOW_ACTIVE";
const SHOW_DONE = "SHOW_DONE";

export default { ADD_TASK, REMOVE_TASK, DONE_TASK, SHOW_ACTIVE, SHOW_ALL, SHOW_DONE, CHANGE_FILTER }